### ISSUE TITLE
LTI autoregister not working properly on OpenEdx

### ISSUE THREAD

**Issue by VirtualDiegox** [JuezUN/INGInious#398]
**Describe the bug / issue**
when an user use the auto register functionality via OpenEdx course, his username is received as an empty string, this means that the plugin wont work because it needs email and username to create the account.

![image](https://user-images.githubusercontent.com/36159478/157691463-750260cd-d00c-4370-b88d-021759a5965f.png)

**Expected behavior**
Given the LTI info, get the username and email of the user in order to create the account.

**Comment by ferestrepoca** [comment]
Automatic webapp restart failed today due to an error on this new plugin. Please revise the following log and verify the steps in the [documentation for creating new plugins](https://github.com/JuezUN/INGInious/wiki/How-to-create-plugins). This was the error log:
![image](https://user-images.githubusercontent.com/11912846/158096786-a5e17043-abbb-4584-abce-c3893bbb8c10.png)
