### ISSUE TITLE
Fix possible (memory leak?) on the graders

### ISSUE THREAD

**Issue by amrondonp** [JuezUN/INGInious#76]
After running for long time, we have seen that some processes just eat up all ram in the system. This processes are closely related to the grading processes, so there is very likely that the resources used for container execution are not being disposed correctly. We need to be able to kill the container and stop making usage of the resources. This can even cause service downtime if the server RAM gets full

**Comment by crdgonzalezca** [comment]
We think this has been already fixed. What we have done is to set an static number of processes of Lighttpd so that way there are not processes creating/dieing dynamically and the grading containers are always killed. 

We have seen a more stable server. We will close this when we are completely sure this problem is fixed.

**Comment by crdgonzalezca** [comment]
This is not happening anymore after the correct configuration of Lighttpd.
I am going to proceed to close it.
